substitutions:
  device_name: efun_sh331_1
  device_comment: "EFUN SH331 Energy Monitoring Smart Plug"

packages:
  common: !include templates/common.yaml
  efun_sh331: !include templates/efun_sh331.yaml
  # web_server: !include templates/web_server.yaml
