substitutions:
  device_name: efun_sh331_1
  device_comment: "EFUN SH331 Energy Monitoring Smart Plug"

<<: !include templates/common.yaml
<<: !include templates/efun_sh331.yaml

web_server:
  port: 80
