substitutions:
  # TODO: Rename "_" to "-"" when online
  device_name: efun_sh331_3
  device_comment: "EFUN SH331 Energy Monitoring Smart Plug"

packages:
  efun_sh331: !include templates/efun_sh331.yaml
