substitutions:
  device_name: esp32-test
  device_comment: "ESP32 Test Device"

esphome:
  name: ${device_name}
  comment: ${device_comment}

esp32:
  board: esp32dev
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain
  reboot_timeout: 5min
  # power_save_mode: none
  fast_connect: true

logger:
  level: debug

api:
  id: api_server
  reboot_timeout: 5min

ota:
  password: !secret ota_password

time:
  - platform: homeassistant
    id: homeassistant_time

debug:
  update_interval: 60s

# esp32_ble_tracker:
#   scan_parameters:
#     active: true

# bluetooth_proxy:
#   active: true

button:
  - platform: restart
    name: ${device_name}_restart

binary_sensor:
  - platform: status
    name: ${device_name}_status

text_sensor:
  - platform: version
    name: ${device_name}_version
  - platform: wifi_info
    ip_address:
      name: ${device_name}_wifi_ip
      id: wifi_ip
      update_interval: 60s
    ssid:
      name: ${device_name}_wifi_ssid
      update_interval: 60s
    bssid:
      name: ${device_name}_wifi_bssid
      update_interval: 60s
  - platform: debug
    device:
      name: ${device_name}_device_info
    reset_reason:
      name: ${device_name}_reset_reason

sensor:
  - platform: wifi_signal
    name: ${device_name}_wifi_signal
    update_interval: 60s
  - platform: uptime
    name: ${device_name}_uptime
    unit_of_measurement: min
    filters:
      - lambda: return x / 60.0;
  - platform: debug
    free:
      name: ${device_name}_heap_free

