substitutions:
  device_name: esp32-s3-test
  device_comment: "ESP32-S3 Test Device"

esphome:
  name: ${device_name}
  comment: ${device_comment}

# https://www.adafruit.com/product/5323#technical-details
# https://learn.adafruit.com/adafruit-esp32-s3-feather/pinouts

esp32:
  # Adafruit ESP32-S3 8MB Flash 5323, 5885 (w.FL)
  # https://docs.platformio.org/en/latest/boards/espressif32/adafruit_feather_esp32s3_nopsram.html
  board: adafruit_feather_esp32s3_nopsram
  # Adafruit ESP32-S3 4MB Flash 2MB PSRAM 5477
  # board: adafruit_feather_esp32s3
  # https://docs.platformio.org/en/latest/boards/espressif32/adafruit_feather_esp32s3.html
  variant: esp32s3
  flash_size: 8MB
  framework:
    type: esp-idf

# https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/issues/121#issuecomment-1840353183
# https://github.com/mu-editor/mu/issues/2313
# https://github.com/esphome/issues/issues/5187
# https://docs.platformio.org/en/latest/boards/espressif32/adafruit_feather_esp32s3_nopsram.html
# https://www.adafruit.com/product/5323
# https://github.com/adafruit/Adafruit-Feather-ESP32-S3-PCB/blob/main/Adafruit%20Feather%20ESP32-S3%20Pinout.pdf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain
  reboot_timeout: 5min
  # power_save_mode: none
  # fast_connect: true

logger:
  level: debug

api:
  id: api_server
  reboot_timeout: 5min

ota:
  password: !secret ota_password

time:
  - platform: homeassistant
    id: homeassistant_time

debug:
  update_interval: 60s

# esp32_ble_tracker:
#   scan_parameters:
#     active: true

# bluetooth_proxy:
#   active: true

button:

  - platform: restart
    name: ${device_name}_restart

binary_sensor:

  - platform: status
    name: ${device_name}_status

text_sensor:

  - platform: version
    name: ${device_name}_version
  - platform: wifi_info
    ip_address:
      name: ${device_name}_wifi_ip
      id: wifi_ip
      update_interval: 60s
    ssid:
      name: ${device_name}_wifi_ssid
      update_interval: 60s
    bssid:
      name: ${device_name}_wifi_bssid
      update_interval: 60s
  - platform: debug
    device:
      name: ${device_name}_device_info
    reset_reason:
      name: ${device_name}_reset_reason

sensor:

  - platform: wifi_signal
    name: ${device_name}_wifi_signal
    update_interval: 60s
  - platform: uptime
    name: ${device_name}_uptime
    unit_of_measurement: min
    filters:
      - lambda: return x / 60.0;
  - platform: debug
    free:
      name: ${device_name}_heap_free

  # MAX17048
  # I2C 0x36
  - platform: max17048
    battery_voltage:
      name: Battery Voltage
    battery_level:
      name: Battery Level
    rate:
      name: Battery Discharge Rate

# I2C
i2c:
  sda: GPIO3
  scl: GPIO4

# BME280
# I2C 0x77
# Not populated

# MAX17048
# https://www.analog.com/en/products/max17048.html
# https://github.com/esphome/feature-requests/issues/2277
# https://github.com/Option-Zero/esphome-components
external_components:
  - source: github://Option-Zero/esphome-components
    components: [max17048]

# NeoPixel / WS2812
# GPIO21 Power
# GPIO33 Data

# https://esphome.io/components/switch/
switch:

  # https://esphome.io/components/switch/gpio
  - platform: gpio
    pin: GPIO21
    name: "NeoPixel Power"
    restore_mode: ALWAYS_ON

# https://esphome.io/components/light/
light:

  # https://esphome.io/components/light/esp32_rmt_led_strip
  - platform: esp32_rmt_led_strip
    name: "NeoPixel"
    rgb_order: GRB
    pin: GPIO33
    num_leds: 1
    rmt_channel: 0
    chipset: WS2812
