# https://esphome.io/guides/configuration-types.html#substitutions
substitutions:
  device_name: esp32-s3-devkitc-test
  device_comment: "Espressif ESP32-S3 DevKitC Test Device"

# https://esphome.io/guides/configuration-types.html#packages
packages:
  feather: !include templates/esp32-s3-devkitc.yaml
