# https://esphome.io/guides/configuration-types.html#substitutions
substitutions:
  device_name: garage-gate-fan
  device_comment: "Sonoff TH10 Garage Gate Fan Thermostat"
  target_temperature_high: "28.0" # ~80F


# https://esphome.io/guides/configuration-types.html#packages
packages:
  sonoff_th10: !include templates/sonoff_th10.yaml
    

# https://esphome.io/components/sensor/index.html    
sensor:

  # https://esphome.io/components/sensor/dallas.html
  - platform: dallas
    address: 0xEB3C01D075FBA928
    name: ${device_name}_temp
    id: temp
    # https://esphome.io/components/sensor/index.html#sliding-window-moving-average-exponential-moving-average
    filters:
      - sliding_window_moving_average:
          window_size: 3
          send_every: 3
          send_first_at: 3


# https://esphome.io/components/climate/index.html
climate:

  # https://esphome.io/components/climate/thermostat.html
  - platform: thermostat
    name: ${device_name}_thermostat
    id: thermo
    sensor: temp
    min_cooling_off_time: 60s 
    min_cooling_run_time: 60s
    min_idle_time: 60s
    cool_action:
      - logger.log: "Thermostat : Cool Action, Turning Relay On."
      - switch.turn_on: relay
    idle_action:
      - logger.log: "Thermostat : Idle Action, Turning Relay Off."
      - switch.turn_off: relay
    default_preset: Default
    preset:
      - name: Default
        default_target_temperature_high: ${target_temperature_high}
    visual:
      min_temperature: 20.0
      max_temperature: 40.0
      temperature_step: 0.5
