# Customized
# https://github.com/ratgdo/esphome-ratgdo/blob/main/static/v25board_esp8266_d1_mini_lite.yaml

# TODO: Consolidate comment and description and prefix

# Substitutions used by templates
substitutions:
  # Substitutions used by local templates
  device_name: garage-door-controller
  device_comment: "RatGDO Garage Door Controller"
  # Substitutions used by ratgdo
  id_prefix: ratgdov25
  friendly_name: "RatGDO v2.5"
  uart_tx_pin: D1
  uart_rx_pin: D2
  input_obst_pin: D7
  status_door_pin: D0
  status_obstruction_pin: D8
  dry_contact_open_pin: D5
  dry_contact_close_pin: D6
  dry_contact_light_pin: D3

# The ratgdo expected ids for time is homeassistant_time and api is api_server
# They happen to match template ids used, no need to double define

# The default ratgdo config includes improv_serial, we don't need it.

# https://esphome.io/components/esphome.html
esphome:
  name: ${device_name}
  comment: ${device_comment}

# https://esphome.io/components/esp8266.html
esp8266:
  board: d1_mini_lite
  restore_from_flash: true

# https://esphome.io/guides/configuration-types.html#local-packages
# https://esphome.io/guides/configuration-types.html#remote-git-packages
packages:
  common: !include templates/common.yaml
  ratgdo_package:
    url: https://github.com/ratgdo/esphome-ratgdo
    files: [base.yaml]
