# https://esphome.io/guides/configuration-types.html#substitutions
substitutions:
  device_name: kincony-kc868asr-test
  device_comment: "Kincony KC868-ASR Test Device"

# https://esphome.io/guides/configuration-types.html#packages
packages:
  kincony: !include templates/kincony-kc868-asr.yaml
