# https://esphome.io/guides/configuration-types.html#substitutions
substitutions:
  device_name: living-room-plant-sensor
  device_friendly_name: "Living Room Plant Sensor"

# https://esphome.io/guides/configuration-types.html#packages
packages:
  plt1b: !include templates/apollo-plt-1b.yaml
