substitutions:
  device_name: m5stack-core-test
  device_comment: "M5Stack Test Device"

esphome:
  name: ${device_name}
  comment: ${device_comment}

esp32:
  board: m5stack-core-esp32

packages:
  common: !include templates/common.yaml
