substitutions:
  device_name: m5stack-core-test
  device_comment: "M5Stack Test Device"

esphome:
  name: ${device_name}
  comment: ${device_comment}
  platform: ESP32
  board: m5stack-core-esp32

packages:
  common: !include templates/common.yaml
  memory_sensor:  !include templates/esp32-memory-sensor.yaml
