# https://esphome.io/components/substitutions
substitutions:
  device_name: music-room-plant-sensor
  device_friendly_name: "Music Room Plant Sensor"

# https://esphome.io/components/packages
packages:
  plt1b: !include templates/apollo-plt-1b.yaml
