substitutions:
  device_name: pantry-bluetooth-proxy
  device_friendly_name: "Pantry Bluetooth Proxy"

packages:
  waveshare: !include templates/waveshare-esp32-s3-eth.yaml

# https://esphome.io/components/esp32_ble_tracker
esp32_ble_tracker:
  scan_parameters:
    active: true

# https://esphome.io/components/bluetooth_proxy
bluetooth_proxy:
  active: true
