# https://esphome.io/guides/configuration-types.html#substitutions
substitutions:
  device_name: rocket-astra-test
  device_comment: "RocketController Astra Test Device"

# https://esphome.io/guides/configuration-types.html#packages
packages:
  norvi: !include templates/rocket-astra.yaml

# https://esphome.io/components/binary_sensor/
binary_sensor:

  # https://esphome.io/components/binary_sensor/gpio.html
  - platform: gpio
    name: ${device_name}_input_1
    id: input_1
    pin:
      number: GPIO34
      inverted: true
  - platform: gpio
    name: ${device_name}_input_2
    id: input_2
    pin:
      number: GPIO35
      inverted: true
  - platform: gpio
    name: ${device_name}_input_3
    id: input_3
    pin:
      number: GPIO36
      inverted: true
  - platform: gpio
    name: ${device_name}_input_4
    id: input_4
    pin:
      number: GPIO39
      inverted: true
