# https://esphome.io/guides/configuration-types.html#substitutions
substitutions:
  device_name: stairs-plant-sensor
  device_friendly_name: "Stairs Plant Sensor"

# https://esphome.io/guides/configuration-types.html#packages
packages:
  plt1b: !include templates/apollo-plt-1b.yaml
