# https://esphome.io/guides/configuration-types.html#substitutions
substitutions:
  device_name: stairs-plant-sensor
  device_friendly_name: "Stairs Plant Sensor"
  sleep_duration_hours: "1"
  prevent_sleep_default: "ON"

# https://esphome.io/guides/configuration-types.html#packages
packages:
  plt1b: !include templates/apollo-plt-1b.yaml
