substitutions:
  device_name: tuya-convert
  device_comment: "Temporary device used during Tuya to Tasmota to ESPHome conversion"

# wifi:
  # use_address: tuya_convert

esphome:
  name: ${device_name}
  comment: ${device_comment}

esp8266:
  board: esp01_1m

packages:
  common: !include templates/common.yaml
  memory_sensor:  !include templates/esp8266-memory-sensor.yaml
