# https://esphome.io/components/substitutions
substitutions:
  device_name: upstairs-hallway-plant-sensor
  device_friendly_name: "Upstairs Hallway Plant Sensor"

# https://esphome.io/components/packages
packages:
  plt1b: !include templates/apollo-plt-1b.yaml
