# https://docs.espressif.com/projects/esp-idf/en/latest/esp32/hw-reference/esp32/get-started-devkitc.html
# https://esphome.io/devices/nodemcu_esp32.html
# LED: GPIO27
# Input 1 : GPIO32
# Input 2 : GPIO33


# https://esphome.io/guides/configuration-types.html#substitutions
substitutions:
  device_name: utility_pulse_counter
  device_comment: "ESP-WROOM-32UE Utility Meter Pulse Counter"


# https://esphome.io/components/esphome.html  
esphome:
  name: ${device_name}
  comment: ${device_comment}
  platform: ESP32
  board: nodemcu-32s


# https://esphome.io/guides/configuration-types.html#packages
packages:
  common: !include templates/common.yaml
  status_sensor: !include templates/status_sensor.yaml
  version_sensor: !include templates/version_sensor.yaml
  wifi_sensor: !include templates/wifi_sensor.yaml
  uptime_sensor:  !include templates/uptime_sensor.yaml
  restart_switch: !include templates/restart_switch.yaml
  # web_server: !include templates/web_server.yaml

  
# https://esphome.io/components/debug.html
debug:


# https://esphome.io/components/status_led.html
status_led:
  pin:
    number: GPIO27
    inverted: true


# https://esphome.io/components/sensor/index.html
sensor:
  # https://esphome.io/components/sensor/pulse_meter.html
  # https://esphome.io/components/sensor/pulse_counter.html
  - platform: pulse_counter
    pin:
      number: GPIO32
      mode: INPUT_PULLUP
    unit_of_measurement: 'gal/min'
    name: 'Water Meter'
    icon: 'mdi:water'
    filters:
      - multiply: 10
  - platform: pulse_counter
    pin:
      number: GPIO33
      mode: INPUT_PULLUP
    unit_of_measurement: 'ft³/min'
    name: 'Gas Meter'
    icon: 'mdi:fire'
    filters:
      - multiply: 10
