# Customized
# https://github.com/tube0013/tube_gateways/blob/main/models/current/tubeszb-cc2652-eth_usb/firmware/esphome/tubezb-cc2652p2-ethusb-2022.yaml

# Substitutions used by templates
substitutions:
  device_name: zigbee-coordinator
  device_comment: "TubesZB CC2652P2 Ethernet Zigbee Zoordinator"

# https://esphome.io/components/esphome.html
esphome:
  name: ${device_name}
  comment: ${device_comment}

# https://esphome.io/components/esp32
esp32:
  board: esp-wrover-kit

# https://esphome.io/guides/configuration-types.html#local-packages
packages:
  common_no_wifi: !include templates/common-no-wifi.yaml

# https://esphome.io/components/external_components.html
# https://github.com/tube0013/esphome-stream-server-v2
# https://github.com/syssi/esphome-zeroconf
external_components:
  - source: github://tube0013/esphome-stream-server-v2@main
  - source: github://syssi/esphome-zeroconf@main

# WT32-ETH01 Ethernet
# https://esphome.io/components/ethernet.html
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16

  # Use a static IP to improve Z2M reliability
  # tubeszb.home.insanegenius.net
  manual_ip:
    static_ip: 192.168.1.6
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.1

script:
  - id: fw_update_mode
    then:
      - switch.turn_on: zBSL
      - delay: 1s
      - switch.turn_on: zRST_gpio
      - delay: 1s
      - switch.turn_off: zRST_gpio
      - logger.log: "Delaying ~10 seconds for cc2652p2 to settle"
      - delay: 11s
      - switch.turn_off: zBSL
      - logger.log: "Please try update with cc2538-bsl tool now"
      - logger.log: "cc-bsl usage: cc2538-bsl.py -p socket://ip-of-gw:6638 -evw firmware.hex"
      
switch:
  - platform: gpio
    pin: 33
    id: zRST_gpio
    inverted: yes
    restore_mode: ALWAYS_OFF
      
  - platform: gpio
    pin: 32
    name: "zBSL"
    id: zBSL
    inverted: yes
    restore_mode: ALWAYS_OFF
    
  - platform: template
    name: "Prep the cc2652p2 for firmware update"
    turn_on_action:
      - script.execute: fw_update_mode
    turn_off_action:
      - button.press: zRST

button:
  - platform: restart
    name: "Restart the Device"

  - platform: template
    name: "Zigbee Module Reset"
    id: zRST
    on_press:
      - switch.turn_on: zRST_gpio
      - delay: 15ms
      - switch.turn_off: zRST_gpio

uart:
  id: uart_bus
  rx_pin: GPIO17
  tx_pin: GPIO5
  baud_rate: 115200

stream_server:
  uart_id: uart_bus
  id: ss
  port: 6638

binary_sensor:
  - platform: stream_server
    stream_server: ss
    name: "TubesZB Serial Connected"

zeroconf:
  - service: tubeszb
    protocol: tcp
    port: 6638
    txt:
      version: 1.0
      name: TubesZB
      radio_type: znp
      baud_rate: 115200
      data_flow_control: software
