# https://esphome.io/components/substitutions
substitutions:
  device_name: kincony-kc868asr-test
  device_comment: "Kincony KC868-ASR Test Device"

# https://esphome.io/components/packages
packages:
  kincony: !include templates/kincony-kc868-asr.yaml
