# https://esphome.io/components/substitutions
substitutions:
  device_name: wemos-lolin32-lite-test
  device_comment: "WEMOS LOLIN32 Lite Test Device"

# https://esphome.io/components/packages
packages:
  feather: !include templates/wemos-lolin32-lite.yaml
