# Adafruit ESP32-S3 Feather
# Adafruit ESP32-S3 8MB Flash 5323, 5885 w.FL
# Adafruit ESP32-S3 4MB Flash 2MB PSRAM 5477

# https://www.adafruit.com/product/5323#technical-details
# https://learn.adafruit.com/adafruit-esp32-s3-feather/pinouts

# Required substitutions:
# device_name
# device_comment

# https://esphome.io/components/esphome
esphome:
  name: ${device_name}
  comment: ${device_comment}

# https://esphome.io/components/esp32
esp32:
  # Adafruit ESP32-S3 8MB Flash 5323, 5885 (w.FL)
  # https://docs.platformio.org/en/latest/boards/espressif32/adafruit_feather_esp32s3_nopsram.html
  board: adafruit_feather_esp32s3_nopsram
  # Adafruit ESP32-S3 4MB Flash 2MB PSRAM 5477
  # board: adafruit_feather_esp32s3
  # https://docs.platformio.org/en/latest/boards/espressif32/adafruit_feather_esp32s3.html
  # board: adafruit_feather_esp32s3
  # variant: esp32s3
  # flash_size: 8MB
  # framework:
  #   type: esp-idf

# https://esphome.io/guides/configuration-types.html#local-packages
packages:
  common: !include common.yaml

# https://esphome.io/components/i2c
i2c:
  sda: GPIO3 # WARNING GPIO3 is a strapping PIN and should only be used for I/O with care.
  scl: GPIO4

# BME280
# I2C 0x77
# Not populated

# MAX17048
# https://www.analog.com/en/products/max17048.html
# https://github.com/esphome/feature-requests/issues/2277
# https://github.com/Option-Zero/esphome-components
external_components:
  - source: github://Option-Zero/esphome-components
    components: [max17048]

# https://esphome.io/components/sensor/
sensor:

  # MAX17048
  # I2C 0x36
  - platform: max17048
    battery_voltage:
      name: ${device_name}_battery_voltage
    battery_level:
      name: ${device_name}_battery_level
    rate:
      name: ${device_name}_battery_discharge_rate

# NeoPixel / WS2812
# GPIO21 Power
# GPIO33 Data

# https://esphome.io/components/switch/
switch:

  # https://esphome.io/components/switch/gpio
  - platform: gpio
    pin: GPIO21
    name: ${device_name}_neopixel_power"
    restore_mode: ALWAYS_ON

# https://esphome.io/components/light/
light:

  # https://esphome.io/components/light/esp32_rmt_led_strip
  - platform: esp32_rmt_led_strip
    name: ${device_name}_neopixel
    rgb_order: GRB
    pin: GPIO33 # WARNING GPIO33 is used by the PSRAM interface on ESP32-S3R8 / ESP32-S3R8V and should be avoided on these models
    num_leds: 1
    rmt_channel: 0
    chipset: WS2812
