# Required substitutions:
# device_name

# https://esphome.io/components/button/
button:

  # https://esphome.io/components/button/restart
  - platform: restart
    name: ${device_name}_restart

# https://esphome.io/components/binary_sensor
binary_sensor:

  # https://esphome.io/components/binary_sensor/status
  - platform: status
    name: ${device_name}_status

# https://esphome.io/components/text_sensor
text_sensor:

  # https://esphome.io/components/text_sensor/version
  - platform: version
    name: ${device_name}_version

# https://esphome.io/components/sensor
sensor:

  # https://esphome.io/components/sensor/uptime
  - platform: uptime
    name: ${device_name}_uptime
    unit_of_measurement: min
    filters:
      - lambda: return x / 60.0;
