# Required substitutions:
# device_name
# device_comment

# https://esphome.io/components/esphome
esphome:
  name: ${device_name}
  comment: ${device_comment}

# https://esphome.io/components/esp32
esp32:
  # https://docs.platformio.org/en/latest/boards/espressif32/esp32dev.html
  board: esp32dev
  # https://esphome.io/components/esp32#esp-idf-framework
  framework:
    type: esp-idf

# https://esphome.io/guides/configuration-types.html#local-packages
packages:
  common: !include common.yaml

# https://esphome.io/components/esp32_ble_tracker.html
esp32_ble_tracker:
  scan_parameters:
    active: true

# https://esphome.io/components/bluetooth_proxy.html
bluetooth_proxy:
  active: true