# Keep in sync with common.yaml
# Remove WiFi related configuration

# https://esphome.io/components/logger
logger:
  level: info # none, error, warn, info, debug, verbose, very_verbose

# https://esphome.io/components/api
api:
  id: api_server
  reboot_timeout: 5min

# https://esphome.io/components/ota
ota:
  password: !secret ota_password

# https://esphome.io/components/time
time:
  # https://esphome.io/components/time/homeassistant
  - platform: homeassistant
    id: homeassistant_time

# https://esphome.io/components/debug
debug:

# https://esphome.io/components/web_server
web_server:
  port: 80

# https://esphome.io/components/button/
button:

  # https://esphome.io/components/button/restart.html
  - platform: restart
    name: ${device_name}_restart

# https://esphome.io/components/binary_sensor
binary_sensor:

  # https://esphome.io/components/binary_sensor/status.html
  - platform: status
    name: ${device_name}_status

# https://esphome.io/components/text_sensor
text_sensor:

  # https://esphome.io/components/text_sensor/version.html
  - platform: version
    name: ${device_name}_version

# https://esphome.io/components/sensor
sensor:

  # https://esphome.io/components/sensor/uptime
  - platform: uptime
    name: ${device_name}_uptime
    unit_of_measurement: min
    filters:
      - lambda: return x / 60.0;
