# Keep in sync with common.yaml
# Remove logger related configuration

# https://esphome.io/components/wifi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain
  reboot_timeout: 5min
  # Do not fallback to AP mode as that requires a physical reset
  # ap:
  #   ssid: ${device_name}_ap
  #   password: !secret wifi_password
  # Specify current address when renaming devices
  # use_address: foo

# https://esphome.io/components/captive_portal
# captive_portal:

# https://esphome.io/components/api
api:
  id: api_server
  reboot_timeout: 5min

# https://esphome.io/components/ota
ota:
  password: !secret ota_password

# https://esphome.io/components/time
time:
  # https://esphome.io/components/time/homeassistant
  - platform: homeassistant
    id: homeassistant_time

# https://esphome.io/components/debug
debug:
  update_interval: 60s

# https://esphome.io/components/web_server
# Disable by default, consumes lots of memory
# web_server:
#   port: 80

# https://esphome.io/components/button/
button:

  # https://esphome.io/components/button/restart.html
  - platform: restart
    name: ${device_name}_restart

# https://esphome.io/components/binary_sensor
binary_sensor:

  # https://esphome.io/components/binary_sensor/status.html
  - platform: status
    name: ${device_name}_status

# https://esphome.io/components/text_sensor
text_sensor:

  # https://esphome.io/components/text_sensor/version.html
  - platform: version
    name: ${device_name}_version

  # https://esphome.io/components/text_sensor/wifi_info.html
  - platform: wifi_info
    ip_address:
      name: ${device_name}_wifi_ip
      id: wifi_ip
      update_interval: 60s
    ssid:
      name: ${device_name}_wifi_ssid
      update_interval: 60s
    bssid:
      name: ${device_name}_wifi_bssid
      update_interval: 60s

  # https://esphome.io/components/debug
  - platform: debug
    device:
      name: ${device_name}_device_info
    reset_reason:
      name: ${device_name}_reset_reason

# https://esphome.io/components/sensor
sensor:

  # https://esphome.io/components/sensor/wifi_signal.html
  - platform: wifi_signal
    name: ${device_name}_wifi_signal
    update_interval: 60s

  # https://esphome.io/components/sensor/uptime
  - platform: uptime
    name: ${device_name}_uptime
    unit_of_measurement: min
    filters:
      - lambda: return x / 60.0;

  # https://esphome.io/components/debug
  - platform: debug
    free:
      name: ${device_name}_heap_free
