# Required substitutions:
# device_name

# https://esphome.io/components/debug
debug:

# https://esphome.io/components/text_sensor
text_sensor:

  # https://esphome.io/components/debug
  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"

# https://esphome.io/components/sensor
sensor:

  # https://esphome.io/components/debug
  - platform: debug
    free:
      name: "Heap Free"
