# ESP32-S3-WROOM-2-N32R8V
# ESP32-S3R8V, 32MB Octal SPI Flash, 8MB Octal SPI PSRAM, 1.8V SPI
# https://www.espressif.com/sites/default/files/documentation/esp32-s3-wroom-2_datasheet_en.pdf

# ESP32-S3-WROOM-2U Not yet released
# https://device.report/m/152f028fce838da7b8ef5fa5d8282e0bbb72428a5f51da4a3dcbf57f3f31c530.pdf
# https://www.espressif.com/sites/default/files/documentation/esp32-s3-wroom-1_wroom-1u_datasheet_en.pdf

# ESP32-S3-WROOM-2 uses Octal memory, ESP32-S3-WROOM-1 uses Quad memory

# GPIO35, GPIO36, GPIO37 : Octal SPI flash PSRAM

# Keep in sync with esp32-s3-wroom-2-n16r8v.yaml

# TODO: Boot log warnings
# "spi_flash: Octal flash chip is using but dio mode is selected, will automatically swich to Octal mode"
# "tsens: legacy driver is deprecated, please migrate to `driver/temperature_sensor.h`"
# "rmt(legacy): legacy driver is deprecated, please migrate to `driver/rmt_tx.h` and/or `driver/rmt_rx.h`"

# TODO: OTA does not work, succeeds but does not actually update the firmware, only USB programming works
# Use max 16MB flash else OTA does not work
# https://github.com/esphome/issues/issues/5824

# https://esphome.io/components/esphome
esphome:
  
  # Modify default esp32-s3-devkitc-1 (8MB Flash, no PSRAM) board configuration
  # https://docs.platformio.org/en/latest/boards/espressif32/esp32-s3-devkitc-1.html
  # https://github.com/platformio/platform-espressif32/blob/master/boards/esp32-s3-devkitc-1.json
  platformio_options:

    # TODO: Does ISP-IDF need a correct partition table defined in Arduino settings?
    # Largest "default" partition type is 16MB default_16MB.csv, no default 32MB partition, closest matching in layout is large_littlefs_32MB.csv
    # https://github.com/espressif/arduino-esp32/tree/master/tools/partitions
    board_build.arduino.partitions: large_littlefs_32MB.csv
    # Octal memory type for Flash and PSRAM
    board_build.arduino.memory_type: opi_opi
    # TODO: How to add elements vs. replace all?
    board_build.extra_flags: 
      - "-DARDUINO_ESP32S3_DEV"
      # Has PSRAM
      - "-DBOARD_HAS_PSRAM"
      - "-DARDUINO_USB_MODE=1"
      - "-DARDUINO_RUNNING_CORE=1"
      - "-DARDUINO_EVENT_RUNNING_CORE=1"
    # Octal memory type for PSRAM
    board_build.psram_type: opi
    board_name: "Espressif ESP32-S3-WROOM-2-N32R8V (ESP32-S3R8V, 32MB Octal SPI Flash, 8MB Octal SPI PSRAM, 1.8V SPI)"
    # TODO: Error when setting flash size in board config?
    # "Please specify flash_size within esp32 configuration only.""
    # board_upload.flash_size: 32MB
    # 32MB
    board_upload.maximum_size: 33554432

# https://esphome.io/components/esp32
esp32:

  # Platformio config changes will modify esp32-s3-devkitc-1 base configuration
  board: esp32-s3-devkitc-1

  # TODO: Why can't we set flash size in board config?
  flash_size: 32MB

  # https://esphome.io/components/esp32#esp-idf-framework
  framework:
    type: esp-idf
    platform_version: ${espressif32_version}
    version: ${espidf_version}
    # TODO: https://github.com/esphome/issues/issues/5404
    # "Warning! Flash memory size mismatch detected. Expected 32MB, found 2MB!"
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_32MB: "y"

# https://esphome.io/components/psram
psram:
  mode: octal
  speed: 80MHz
