# Espressif ESP32-S3-DevKitC-1/1U
# https://docs.espressif.com/projects/esp-idf/en/stable/esp32s3/hw-reference/esp32s3/user-guide-devkitc-1.html

# ESP32-S3-WROOM-1-N8       : 8MB  Flash, 0MB PSRAM, 3.3V
# ESP32-S3-WROOM-1-N8R2     : 8MB  Flash, 2MB PSRAM, 3.3V
# ESP32-S3-WROOM-1-N8R8     : 8MB  Flash, 8MB PSRAM, 3.3V
# ESP32-S3-WROOM-2-N16R8V   : 16MB Flash, 8MB PSRAM, 1.8V
# ESP32-S3-DEVKITC-1-N32R8V : 32MB Flash, 8MB PSRAM, 1.8V
# ESP32-S3-WROOM-1U-N8      : 8MB  Flash, 0MB PSRAM, 3.3V
# ESP32-S3-WROOM-1U-N8R2    : 8MB  Flash, 2MB PSRAM, 3.3V
# ESP32-S3-DEVKITC-1U-N8R8  : 8MB  Flash, 8MB PSRAM, 3.3V

# GPIO38 : RGB LED

# Required substitutions:
# device_name
# device_comment

# TODO: esp_core_dump_flash: No core dump partition found!
# https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/core_dump.html#save-core-dump-to-flash

# https://esphome.io/components/esphome
esphome:
  name: ${device_name}
  comment: ${device_comment}
  platformio_options:
    # TODO: Required else bootloop after programming
    board_build.arduino.memory_type: opi_opi

# https://esphome.io/components/esp32
esp32:
  # https://docs.platformio.org/en/latest/boards/espressif32/esp32-s3-devkitc-1.html
  board: esp32-s3-devkitc-1
  # TODO: Match board type
  flash_size: 32MB

  # https://esphome.io/components/esp32#esp-idf-framework
  framework:
    # TODO: Temperature sensor requires ESP-IDF 4.4.3+
    # https://github.com/esphome/issues/issues/4271
    type: arduino
    version: latest

# https://esphome.io/guides/configuration-types.html#local-packages
packages:
  common: !include common.yaml
  temperature: !include temperature.yaml

# TODO: Match board type
# https://esphome.io/components/psram
psram:
  mode: octal
  speed: 80MHz

# https://esphome.io/components/light/
light:

  # https://esphome.io/components/light/esp32_rmt_led_strip
  - platform: esp32_rmt_led_strip
    name: ${device_name}_rgb_led
    id: rgb_led
    rgb_order: GRB
    pin: GPIO38
    num_leds: 1
    rmt_channel: 0
    chipset: WS2812

  # TODO: Add status RGB LED
  # https://github.com/esphome/esphome/pull/5814
  
  # https://esphome.io/components/light/status_led
  - platform: status_led
    name: ${device_name}_status_led
    # TODO: How to hide from HA when internal does not seem to work?
    internal: true
    output: status_output

# https://esphome.io/components/output/
output:

  # https://esphome.io/components/output/template.html
  - platform: template
    id: status_output
    type: binary
    write_action:
      - if:
          condition:
             lambda: return state > 0;
          then:
            - light.turn_on: 
                id: rgb_led
                red: 100%
                green: 0%
                blue: 0%
                brightness: 25%
          else:
            - light.turn_on: 
                id: rgb_led
                red: 0%
                green: 100%
                blue: 0%
                brightness: 25%
