# Espressif ESP32-S3-DevKitC-1/1U
# https://docs.espressif.com/projects/esp-idf/en/stable/esp32s3/hw-reference/esp32s3/user-guide-devkitc-1.html

# ESP32-S3-WROOM-1-N8       : 8MB  Quad Flash, 0MB      PSRAM, 3.3V SPI
# ESP32-S3-WROOM-1-N8R2     : 8MB  Quad Flash, 2MB Quad PSRAM, 3.3V SPI
# ESP32-S3-WROOM-1-N8R8     : 8MB  Quad Flash, 8MB Octa PSRAM, 3.3V SPI
# ESP32-S3-WROOM-2-N16R8V   : 16MB Octa Flash, 8MB Octa PSRAM, 1.8V SPI
# ESP32-S3-WROOM-2-N32R8V   : 32MB Octa Flash, 8MB Octa PSRAM, 1.8V SPI
# ESP32-S3-DEVKITC-1-N32R8V : 32MB Octa Flash, 8MB Octa PSRAM, 1.8V SPI
# ESP32-S3-WROOM-1U-N8      : 8MB  Quad Flash, 0MB      PSRAM, 3.3V SPI
# ESP32-S3-WROOM-1U-N8R2    : 8MB  Quad Flash, 2MB Quad PSRAM, 3.3V SPI
# ESP32-S3-DEVKITC-1U-N8R8  : 8MB  Quad Flash, 8MB Octa PSRAM, 3.3V SPI

# GPIO35, GPIO36, GPIO37 : Octal SPI flash PSRAM
# GPIO38 : RGB LED
# GPIO43, GPIO44 : SiLabs CP210x USB-UART
# GPIO19, GPIO20 : USB-CDC

# Required substitutions:
# device_name
# device_comment

# https://esphome.io/guides/configuration-types.html#substitutions
substitutions:
  # Used by rgb-led-status.yaml
  rgb_led_pin: GPIO38

# https://esphome.io/components/esphome
esphome:
  name: ${device_name}
  comment: ${device_comment}

# https://esphome.io/components/esp32
esp32:

  # Default board config is for 8MB Quad Flash and no PSRAM
  # https://docs.platformio.org/en/latest/boards/espressif32/esp32-s3-devkitc-1.html
  # https://github.com/platformio/platform-espressif32/blob/master/boards/esp32-s3-devkitc-1.json
  board: esp32-s3-devkitc-1

  # https://esphome.io/components/esp32#esp-idf-framework
  framework:
    # TODO: Need to use the latest version of IDF framework else we get boot crash loops
    type: esp-idf
    # TODO: "latest" for platform_version is not supported, need an exact version number
    # https://registry.platformio.org/platforms/platformio/espressif32/versions
    platform_version: 6.7.0
    # TODO: "latest" for version does not use the latest version, it uses the version matching the platform_release version
    # https://registry.platformio.org/tools/platformio/framework-espidf
    version: 5.2.1

# https://esphome.io/guides/configuration-types.html#local-packages
packages:
  # TODO: Match Flash and PSRAM config for actual board
  # n16r8v: !include esp32-s3-wroom-2-n16r8v.yaml
  common: !include common.yaml
  temperature: !include temperature.yaml
  rgbledstatus: !include rgb-led-status.yaml

# TODO: Match programmer setup
# Log to USB-UART port
# https://esphome.io/components/logger
logger:
  hardware_uart: UART0 # UART0, USB_CDC, USB_SERIAL_JTAG
