# Required substitutions:
# device_name
# device_friendly_name

# Konnected blaQ Garage Door Controller
# https://konnected.io/products/smart-garage-door-opener-blaq-myq-alternative
# https://github.com/konnected-io/konnected-esphome/blob/master/garage-door-GDOv2-Q.yaml
# https://github.com/konnected-io/konnected-esphome/tree/master/components/secplus_gdo

# WARNING Using `cover.COVER_SCHEMA` is deprecated and will be removed in ESPHome 2025.11.0.
# Please use `cover.cover_schema(...)` instead.
# WARNING Using `lock.LOCK_SCHEMA` is deprecated and will be removed in ESPHome 2025.11.0.
# Please use `lock.lock_schema(...)` instead.
# If you are seeing this, report an issue to the external_component author and ask them to update it.
# https://developers.esphome.io/blog/2025/05/14/_schema-deprecations/.
# Component using this schema: secplus_gdo

substitutions:
  # Used by garage-door-GDOv2-Q.yaml
  name: ${device_name}
  friendly_name: ${device_friendly_name}

# https://esphome.io/components/esphome
esphome:
  name: ${device_name}
  friendly_name: ${device_friendly_name}
  name_add_mac_suffix: false

# https://esphome.io/guides/configuration-types.html#local-packages
packages:
  # https://github.com/konnected-io/konnected-esphome/blob/master/garage-door-GDOv2-Q.yaml
  gdov2q: github://konnected-io/konnected-esphome/garage-door-GDOv2-Q.yaml@master
  api: !include api.yaml
  logger: !include logger.yaml
  ota: !include ota.yaml
  time: !include time.yaml
  # TODO: Is there a way to include packages again after removing some items?
  # wifi: !include wifi.yaml

# Remove unwanted items included by gdov2q package
esp32_improv: !remove
dashboard_import: !remove
web_server: !remove
improv_serial: !remove
captive_portal: !remove
wifi:
  ap: !remove
  # Add wifi configuration back after removing AP mode
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain
  reboot_timeout: 15min
  min_auth_mode: WPA2
logger:
  level: !remove
  logs: !remove

# Change uptime sensor to minutes
sensor:
  - id: !extend uptime_sensor
    name: "Uptime"
    unit_of_measurement: min
    filters:
      - lambda: return x / 60.0;

# Change version sensor name
text_sensor:
  - id: !extend esphome_version
    name: "Version"

# Add status sensor
binary_sensor:
  - platform: status
    name: "Status"