# Konnected blaQ Garage Door Controller
# https://konnected.io/products/smart-garage-door-opener-blaq-myq-alternative
# https://github.com/konnected-io/konnected-esphome/blob/master/garage-door-GDOv2-Q.yaml
# https://github.com/konnected-io/konnected-esphome/tree/master/components/secplus_gdo

# Required substitutions:
# device_name
# device_comment

# WARNING Using `cover.COVER_SCHEMA` is deprecated and will be removed in ESPHome 2025.11.0.
# Please use `cover.cover_schema(...)` instead.
# WARNING Using `lock.LOCK_SCHEMA` is deprecated and will be removed in ESPHome 2025.11.0.
# Please use `lock.lock_schema(...)` instead.
# If you are seeing this, report an issue to the external_component author and ask them to update it.
# https://developers.esphome.io/blog/2025/05/14/_schema-deprecations/.
# Component using this schema: secplus_gdo

substitutions:
  # Used by garage-door-GDOv2-Q.yaml
  name: ${device_name}
  # Set friendly_name to device_name
  # https://community.konnected.io/t/use-of-friendly-name-overrides-default-device-name-in-entity-naming/39062
  friendly_name: ${device_name}

# https://esphome.io/components/esphome
esphome:
  name: ${device_name}
  comment: ${device_comment}
  name_add_mac_suffix: false

# https://esphome.io/guides/configuration-types.html#local-packages
packages:
  gdov2q: github://konnected-io/konnected-esphome/garage-door-GDOv2-Q.yaml@master
  api: !include api.yaml
  logger: !include logger.yaml
  ota: !include ota.yaml
  time: !include time.yaml
  wifi: !include wifi.yaml

# Remove unwanted items from gdov2q package
esp32_improv: !remove
dashboard_import: !remove
web_server: !remove
improv_serial: !remove
captive_portal: !remove
wifi:
  # Remove AP fallback
  ap: !remove
# ERROR Error while reading config: The local log level VERBOSE for esp-idf must be less severe than the global log level DEBUG
logger:
  # Inherit from default logger level
  logs: !remove

# Remove device_class: signal_strength from wifi_signal_pct, set device_class: ""
# https://github.com/konnected-io/konnected-esphome/issues/76
sensor:
  - id: !extend wifi_signal_pct
    device_class: ""

# TODO:
# WARNING Found and merged multiple configurations for ota platform esphome port(s) [3232]

# TODO: https://github.com/konnected-io/konnected-esphome/issues/84
#/cache/data/packages/8735b6a9/packages/mdns.yaml: In lambda function:
#/cache/data/packages/8735b6a9/packages/mdns.yaml:14:14: error: 'USE_WEBSERVER_PORT' was not declared in this scope
#   14 |       txt:
#      |              ^