# Required substitutions:
# device_name
# device_comment

# https://esphome.io/devices/sonoff.html#sonoff-th10-th16
# https://templates.blakadder.com/sonoff_TH.html
# https://tasmota.github.io/docs/devices/Sonoff-TH/

# Button: GPIO0, Inverted
# Relay, Red LED: GPIO12
# Blue LED: GPIO13, Inverted
# UART Tx : GPIO1
# UART Rx : GPIO3
# Sensor 1 : GPIO4
# Sensor 2 : GPIO14
# EXP-LOG : GPIO2

# https://www.superhouse.tv/21-six-sonoff-secrets/
# https://tinkerman.cat/post/sonoff-th10-th16-sensors-displays-actuators/

# Tip : GPIO14 (BME280 SDA) (Red)
# Ring 1 : GPIO4 (BME280 SCL) (White)
# Ring 2 : GND (Green)
# Sleeve : 3.3V (Black)

# https://esphome.io/components/esphome.html
esphome:
  name: ${device_name}
  comment: ${device_comment}

# https://esphome.io/components/esp8266
esp8266:
  board: esp8285

# https://esphome.io/guides/configuration-types.html#packages
packages:
  common: !include common.yaml
  memory_sensor:  !include esp8266-memory-sensor.yaml

# https://esphome.io/components/binary_sensor/index.html
binary_sensor:

  # https://esphome.io/components/binary_sensor/gpio.html
  - platform: gpio
    name: ${device_name}_button
    device_class: power
    # https://esphome.io/guides/configuration-types.html#config-pin-schema
    pin:
      number: GPIO0
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      - switch.toggle: relay

# https://esphome.io/components/switch
switch:

  # https://esphome.io/components/switch/gpio.html
  - platform: gpio
    name: ${device_name}_relay
    id: relay
    pin: GPIO12
    restore_mode: ALWAYS_OFF

# https://esphome.io/components/status_led
status_led:
  pin: GPIO13

# https://esphome.io/components/sensor/dallas.html
dallas:
  - pin: GPIO14
