# Required substitutions:
# device_name
# device_comment

# https://tasmota.github.io/docs/devices/Sonoff-S31/
# https://templates.blakadder.com/sonoff_S31.html
# https://www.esphome-devices.com/devices/Sonoff-S31

# Button: GPIO0, Inverted
# CSE7766 Tx: GPIO1
# CSE7766 Rx: GPIO3
# Relay: GPIO12 (Connected to Red LED)
# Blue LED: GPIO13

# https://esphome.io/components/esphome.html
esphome:
  name: ${device_name}
  comment: ${device_comment}

# https://esphome.io/components/esp8266
esp8266:
  board: esp01_1m

# https://esphome.io/components/logger.html
logger:
  # Disable UART logging, it is used for the CSE7766
  baud_rate: 0

# https://esphome.io/components/uart.html
uart:
  rx_pin: RX
  baud_rate: 4800

# https://esphome.io/guides/configuration-types.html#packages
packages:
  # UART is in use, do not log over UART
  common: !include common-no-logger.yaml

# https://esphome.io/components/binary_sensor/index.html
binary_sensor:

  # https://esphome.io/components/binary_sensor/gpio.html
  - platform: gpio
    name: ${device_name}_button
    device_class: power
    # https://esphome.io/guides/configuration-types.html#config-pin-schema
    pin:
      number: GPIO0
      inverted: true
      mode: INPUT_PULLUP
    # Toggle relay state on button press
    on_press:
      - switch.toggle: relay

# https://esphome.io/components/switch/index.html
switch:

  # https://esphome.io/components/switch/gpio.html
  - platform: gpio
    name: ${device_name}_relay
    id: relay
    pin: GPIO12
    # Off on power-on
    restore_mode: ALWAYS_OFF

# https://esphome.io/components/status_led.html
status_led:
  pin:
    number: GPIO13

# https://esphome.io/components/sensor/index.html
sensor:

  # https://esphome.io/components/sensor/cse7766.html
  - platform: cse7766
    update_interval: 15s
    current:
      name: ${device_name}_current
    voltage:
      name: ${device_name}_voltage
    power:
      id: wattage
      name: ${device_name}_power

  # https://esphome.io/components/sensor/total_daily_energy.html
  - platform: total_daily_energy
    name: ${device_name}_total_daily_energy
    power_id: wattage
