# Required substitutions:
# device_name

# TODO: Temperature sensor requires ESP-IDF 4.4.3+
# https://github.com/esphome/issues/issues/4271

# https://esphome.io/components/sensor
sensor:

  # https://esphome.io/components/internal_temperature
  - platform: internal_temperature
    name: ${device_name}_internal_temperature
