# Required substitutions:
# device_name

# https://esphome.io/components/sensor
sensor:

  # https://esphome.io/components/sensor/internal_temperature
  - platform: internal_temperature
    name: "Internal Temperature"
