# External usage:
# packages:
#   temperature: github://ptr727/ESPHome-Config/templates/temperature.yaml@main

# Required substitutions:
# device_name

# https://esphome.io/components/sensor
sensor:

  # https://esphome.io/components/sensor/internal_temperature
  - platform: internal_temperature
    name: "Internal Temperature"
